// <auto-generated />
using AirlinesApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirlinesApp.Migrations
{
    [DbContext(typeof(AirLineDBContext))]
    [Migration("20221026080005_initialmigration5")]
    partial class initialmigration5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AirlinesApp.Models.Airline", b =>
                {
                    b.Property<int>("flightNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("flightNo"), 1L, 1);

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Fare")
                        .HasColumnType("float");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalSeat")
                        .HasColumnType("int");

                    b.HasKey("flightNo");

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            flightNo = 101,
                            Destination = "Destination1",
                            Fare = 100.0,
                            Source = "Source1",
                            TotalSeat = 108
                        },
                        new
                        {
                            flightNo = 102,
                            Destination = "Destination2",
                            Fare = 100.0,
                            Source = "Source2",
                            TotalSeat = 108
                        },
                        new
                        {
                            flightNo = 103,
                            Destination = "Destination3",
                            Fare = 100.0,
                            Source = "Source3",
                            TotalSeat = 108
                        });
                });

            modelBuilder.Entity("AirlinesApp.Models.BookTicket", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassengerId"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassengerFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassengerLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("flightNo")
                        .HasColumnType("int");

                    b.HasKey("PassengerId");

                    b.HasIndex("flightNo");

                    b.ToTable("BookTicket");

                    b.HasData(
                        new
                        {
                            PassengerId = 1,
                            Age = 27,
                            City = "Thalassery",
                            PassengerFirstName = "Prageeth",
                            PassengerLastName = "Rajan",
                            flightNo = 101
                        });
                });

            modelBuilder.Entity("AirlinesApp.Models.CustomerCare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CustomerCare");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "myselfprageeth@gmail.com",
                            PhoneNumber = 9746689742L
                        });
                });

            modelBuilder.Entity("AirlinesApp.Models.BookTicket", b =>
                {
                    b.HasOne("AirlinesApp.Models.Airline", "Airline")
                        .WithMany("BookTickets")
                        .HasForeignKey("flightNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("AirlinesApp.Models.Airline", b =>
                {
                    b.Navigation("BookTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
